### ISSUE TITLE
[GSD-12641] USM device allocation fails with UR_RESULT_ERROR_OUT_OF_DEVICE_MEMORY when Level Zero context spans 2 discrete Arc A770 GPUs (regression from 25.40 to 26.09)

### ISSUE THREAD

**Issue by fradav** [intel/compute-runtime#916]
### Pre-submission Checklist

- [x] I am using the latest GPU driver version ([releases](https://github.com/intel/compute-runtime/releases))
- [x] I have searched for similar issues and found none

### GPU Hardware

2× Intel Arc A770 (DG2, rev 08), 16 GiB each

### DRI Devices Information

```
$ ls -ls /dev/dri/*
0 crw-rw---- 1 root video  226,   0 Apr 17 11:07 /dev/dri/card0
0 crw-rw---- 1 root video  226,   1 Apr 17 11:07 /dev/dri/card1
0 crw-rw-rw- 1 root render 226, 128 Apr 17 11:07 /dev/dri/renderD128
0 crw-rw-rw- 1 root render 226, 129 Apr 17 11:07 /dev/dri/renderD129

$ ls -la /dev/dri/by-path/
total 0
lrwxrwxrwx 1 root root  8 Apr 17 11:07 pci-0000:0d:00.0-card -> ../card0
lrwxrwxrwx 1 root root 13 Apr 17 11:07 pci-0000:0d:00.0-render -> ../renderD128
lrwxrwxrwx 1 root root  8 Apr 17 11:07 pci-0000:11:00.0-card -> ../card1
lrwxrwxrwx 1 root root 13 Apr 17 11:07 pci-0000:11:00.0-render -> ../renderD129
```

### GPU Detailed Information (lspci output)

```
$ sudo lspci -vvv -k -s 0000:0d:00.0
0d:00.0 VGA compatible controller: Intel Corporation DG2 [Arc A770] (rev 08) (prog-if 00 [VGA controller])
        Subsystem: Intel Corporation Device 1020
        Region 0: Memory at fb000000 (64-bit, non-prefetchable) [size=16M]
        Region 2: Memory at f800000000 (64-bit, prefetchable) [size=16G]
        LnkCap: Port #0, Speed 2.5GT/s, Width x1
        LnkSta: Speed 2.5GT/s, Width x1
        Kernel driver in use: xe
        Kernel modules: i915, xe

$ sudo lspci -vvv -k -s 0000:11:00.0
11:00.0 VGA compatible controller: Intel Corporation DG2 [Arc A770] (rev 08) (prog-if 00 [VGA controller])
        Subsystem: Intel Corporation Device 1020
        Region 0: Memory at f9000000 (64-bit, non-prefetchable) [size=16M]
        Region 2: Memory at f000000000 (64-bit, prefetchable) [size=16G]
        LnkCap: Port #0, Speed 2.5GT/s, Width x1
        LnkSta: Speed 2.5GT/s, Width x1
        Kernel driver in use: xe
        Kernel modules: i915, xe
```

### Driver Version

26.09.37435.1

### Installed GPU Driver Packages

```
$ pacman -Q | grep -iE "intel|level.zero|igc|gmmlib|opencl|compute-runtime|ze"
intel-compute-runtime 26.09.37435.1-1
intel-gmmlib 22.9.0-2
intel-graphics-compiler-bin 1:2.30.1-1
intel-media-driver 25.4.6-1
intel-metee 6.2.1-1
intel-oneapi-basekit-2025 2025.3.1-6
intel-xpumanager-bin 1.3.5-1
level-zero-headers 1.28.0-1
level-zero-loader 1.28.0-1
vulkan-intel 1:26.0.4-1
```

### Driver Installation Details

- Installation method: Arch Linux official extra repository (pacman)
- Command: `sudo pacman -S intel-compute-runtime`
- Repository: Arch extra (https://archlinux.org/packages/extra/x86_64/intel-compute-runtime/)
- No custom kernel parameters for the driver itself; xe driver forced via boot params: `xe.force_probe=56a0 i915.force_probe=!56a0`

### Linux Distribution

Arch Linux

### Kernel Version & Boot Parameters

```
$ uname -r
6.19.11-arch1-1

$ cat /proc/cmdline
initrd=\initramfs-linux.img root=UUID=c68104cc-894e-4ccb-a8dd-d0fd2275a9a3 resume=UUID=8d90b58e-8569-45e5-8d71-15d924a7bc74 rw i915.force_probe=!56a0 xe.force_probe=56a0

$ lsmod | grep -E 'i915|xe'
xe                   4227072  6
intel_vsec             28672  1 xe
drm_ttm_helper         20480  1 xe
drm_suballoc_helper    16384  1 xe
gpu_sched              69632  1 xe
drm_gpuvm              57344  1 xe
drm_exec               12288  2 drm_gpuvm,xe
drm_gpusvm_helper      40960  1 xe
i915                 4943872  0
drm_buddy              32768  2 xe,i915
ttm                   126976  3 drm_ttm_helper,xe,i915
drm_display_helper    286720  2 xe,i915
```

Note: i915 is loaded but has 0 uses (force-probed away from DG2 via i915.force_probe=!56a0). xe is the active KMD for both Arc A770 cards.

### Actual Behavior

When running any PyTorch XPU workload (torch 2.11.0+xpu) with 2 discrete Intel Arc A770 GPUs present, the Unified Runtime (UR) layer creates a Level Zero context spanning both devices (`urContextCreate(.DeviceCount = 2)`), then immediately fails on `urUSMDeviceAlloc` with `UR_RESULT_ERROR_OUT_OF_DEVICE_MEMORY`, despite each GPU having 16 GiB of free VRAM.

The Python exception raised is:
```
RuntimeError: could not create a memory buffer of 2097152 bytes
```

This results in the application being completely unable to allocate any tensor on the XPU device.

### Expected Behavior

USM device memory allocation should succeed when a Level Zero context spans 2 discrete root devices, as it did with intel-compute-runtime 25.40.35563.4. Each GPU has 16 GiB of VRAM and the allocation request is only 2 MiB.

### Reproduction Rate

Always reproduces - 100%

### Steps to Reproduce

1. Install intel-compute-runtime 26.09.37435.1 on Arch Linux
2. Install PyTorch with XPU support: `pip install torch==2.11.0+xpu --index-url https://download.pytorch.org/whl/xpu`
3. Ensure 2 discrete Intel Arc A770 GPUs are present and enumerated (both visible in `/dev/dri/`)
4. Run the following Python script:
```python
import torch
print(torch.xpu.device_count())  # prints 2
x = torch.zeros(1, device='xpu:0')  # FAILS here
```
5. Observe `RuntimeError: could not create a memory buffer of 2097152 bytes`

**Workaround**: Set `export ONEAPI_DEVICE_SELECTOR=level_zero:0` before running — this restricts UR to a single-device context and allocations succeed.

### Is this a regression?

- [x] Yes, this is a regression - functionality that previously worked is now broken

### Last Known Working Driver Version

25.40.35563.4

### First Known Failing Driver Version

26.09.37435.1

### API Call Logs

UR trace captured using `UR_LOG_TRACING=output:file:minimal.log;level:info` (binary format, key excerpts below):

```
<--- urContextCreate(.DeviceCount = 2, .phDevices = {0x325bd5a0, 0x325bd5c0}, .pProperties = nullptr, .phContext = ...) -> UR_RESULT_SUCCESS;

---> urUSMDeviceAlloc
<--- urUSMDeviceAlloc(.hContext = 0x34921e00, .hDevice = 0x325bd5a0,
     .pUSMDesc = {.align = 512}, .pool = nullptr,
     .size = 2097152, .ppMem = nullptr) -> UR_RESULT_ERROR_OUT_OF_DEVICE_MEMORY;

---> urUSMDeviceAlloc
<--- urUSMDeviceAlloc(.hContext = 0x34921e00, .hDevice = 0x325bd5a0,
     .pUSMDesc = {.align = 512}, .pool = nullptr,
     .size = 2097152, .ppMem = nullptr) -> UR_RESULT_ERROR_OUT_OF_DEVICE_MEMORY;
```

Key observation: context is created with DeviceCount=2 (both Arc A770s). Every subsequent USM allocation fails immediately. With ONEAPI_DEVICE_SELECTOR=level_zero:0, context is DeviceCount=1 and all allocations succeed.

Suspected root cause: commit 7bb2d32 "performance: enable l0 device usm growing pools" (merged ~Oct 2025) changed `useUsmPoolManager` default from false to true. The growing pool allocator appears to fail when the L0 context spans multiple root devices.

### System Logs / dmesg Output

No GPU errors or warnings in dmesg. Both cards load cleanly:

```
$ sudo dmesg | grep -iE 'xe|drm' | grep -iE 'error|warn|fail|memory|OOM'
(no output - clean driver load)
```

### Source Code / Reproducer

Minimal Python reproducer (requires torch 2.11.0+xpu and 2 discrete Intel Arc GPUs):

```python
import torch

# This will print 2 with 2 Arc A770 cards
print(f"XPU device count: {torch.xpu.device_count()}")

# This fails with UR_RESULT_ERROR_OUT_OF_DEVICE_MEMORY under 26.09
# Works fine under 25.40 or with ONEAPI_DEVICE_SELECTOR=level_zero:0
x = torch.zeros(1, device='xpu:0')
print("Success:", x)
```

Run with:
```bash
pip install torch==2.11.0+xpu --index-url https://download.pytorch.org/whl/xpu
python reproducer.py
```

For UR-level tracing:
```bash
UR_LOG_TRACING=output:file:trace.log;level:info python reproducer.py
strings trace.log | grep -E "urContextCreate|urUSMDeviceAlloc|UR_RESULT"
```

### Command Line / Application Details

```bash
# Reproduces with:
python reproducer.py

# Does NOT reproduce with (workaround):
ONEAPI_DEVICE_SELECTOR=level_zero:0 python reproducer.py
```

### Additional Notes

- The bug is specific to having **2 or more discrete root devices** in the Level Zero context. With a single GPU (or with ONEAPI_DEVICE_SELECTOR restricting to one), all allocations succeed.
- The suspected culprit commit is `7bb2d32` ("performance: enable l0 device usm growing pools") which enables `useUsmPoolManager=true` by default. This was introduced between 25.40 and 26.09.
- Attempted workarounds that did NOT help:
  - `NEO_EnableUsmAllocationPoolManager=0`
  - `NEO_EnableDeviceUsmAllocationPool=0`
  - Both had no effect (UR trace unchanged)
- Related upstream issue (PyTorch side): https://github.com/pytorch/pytorch/issues/164966
- Context: this is triggered by PyTorch XPU (torch 2.11.0+xpu) which uses the UR adapter `libur_adapter_level_zero.so.0` bundled with PyTorch (UR 0.11.x). The UR adapter itself calls into intel-compute-runtime's Level Zero implementation.

**Comment by kgibala** [comment]
Hi @fradav,

Thank you for taking the time to provide this detailed report. We appreciate all the information shared and the regression data marked.

We will further analyze and isolate this issue internally, and will follow up once we have something meaningful to share.

Thank you again for your contribution and cooperation.

**Comment by kgibala** [comment]
Hi @fradav,

Thank you for your patience.

We attempted to reproduce and isolate the reported issue internally, however, we were unable to observe the problem on our side. The checks were performed on two separate setups:

- Setup 1 - Ubuntu 24.04:
```
clinfo | grep "Driver Version"
Driver Version                                  26.09.37435.1
Driver Version                                  26.09.37435.1
```
```
python run.py
2
```
```
python run_1.py
XPU device count: 2
Success: tensor([0.], device='xpu:0')
```
```
uname -r
6.17.0-14-generic
```
- Setup 2 - Docker:
```
python -c "import torch; print('XPU devices:', torch.xpu.device_count())"
UserWarning: Failed to initialize NumPy: No module named 'numpy'
(Triggered internally at cpu = _conversion_method_template(device=torch.device("cpu"))
XPU devices: 2
```
```
python -c "
import torch
print('Device 0:', torch.xpu.get_device_name(0))
print('Device 1:', torch.xpu.get_device_name(1))
x = torch.ones(3, 3, device='xpu:0')
print(x)
print('XPU compute works!')
"
UserWarning: Failed to initialize NumPy: No module named 'numpy'
(Triggered internally at cpu = _conversion_method_template(device=torch.device("cpu"))
Device 0: Intel(R) Arc(TM) A770 Graphics
Device 1: Intel(R) Arc(TM) A770 Graphics
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='xpu:0')
XPU compute works!
```
```
uname -r
6.17.0-14-generic
```
```
pacman -Q intel-compute-runtime
intel-compute-runtime 26.14.37833.4-1
```
```
pacman -Ql intel-compute-runtime | grep -i "ze_intel\|level.zero\|libze"
...
intel-compute-runtime /usr/lib/libze_intel_gpu.so
intel-compute-runtime /usr/lib/libze_intel_gpu.so.1
intel-compute-runtime /usr/lib/libze_intel_gpu.so.1.15.37833
```
----
Could you please try to reproduce the issue on a clean, latest release environment, or alternatively on an Ubuntu OS stack? This would help us narrow down whether the issue is environment-specific.

Thank you for your cooperation.

**Comment by david-bue** [comment]
## Independent reproduction on 2× Arc Pro B70 (BMG-G31), and the pool-manager hypothesis is wrong

I can reproduce this on a different hardware SKU, 2× Intel Arc Pro B70 Limited Edition (BMG-G31, PCI ID 0xe223), 32 GB each, on Fedora 44 with `xe` driver, kernel 7.0.4. Same failure signature: every `urUSMDeviceAlloc` returns `UR_RESULT_ERROR_OUT_OF_DEVICE_MEMORY` the moment the L0 context has `DeviceCount >= 2`, regardless of allocation size, with plenty of free VRAM.

So this is reproducible across DG2 (Alchemist) and BMG (Battlemage), both Xe-architecture root devices via the `xe` KMD on BMG and `xe`/`i915` on DG2. The bug is not hardware-specific within the supported NEO platforms.

### The pool-manager hypothesis (commit `7bb2d32`) is not the cause

I tested this several ways. Reproduction commands available on request; the headline results:

**1. Built `26.14.37833.4` from source with `7bb2d32` reverted.** Verified the revert applied to `level_zero/core/source/driver/driver_handle.cpp` line 437 (`useUsmPoolManager = false` for `initDeviceUsmAllocPool`). **Same failure.**

**2. Built `26.05.37020.3` from source with `7bb2d32` reverted.** Same result. **Same failure.**

**3. Built `25.40.35563.10` from source.** Multi-device contexts **work**. So the regression is in the `25.40.x → 26.05.x` window, but the commit named in this issue is not the culprit.

**4. Set `UR_L0_DISABLE_USM_ALLOCATOR=1` and `SYCL_PI_LEVEL_ZERO_DISABLE_USM_ALLOCATOR=1`** to fully disable UR's pool manager (which routes through `unified-runtime/source/adapters/level_zero/v2/usm.cpp:46` to return `std::nullopt` from `initializeDisjointPoolConfig`, bypassing the disjoint pool entirely). **Same failure.**

**5. Side-loaded Ubuntu 26.04's `libze-intel-gpu1_26.05.37020.3-1_amd64v3.deb`** into a parallel prefix and `LD_LIBRARY_PATH`-prepended it. Verified with `LD_DEBUG=libs` that the Ubuntu-built NEO + L0 loader + gmmlib were actually loaded. **Same failure.** So Ubuntu's literal binary fails identically in my environment, meaning whatever Ubuntu users do to make their setups work, it isn't NEO-version-specific.

**6. UR trace** (key excerpt):

```
urContextCreate(.DeviceCount = 2, ...) -> UR_RESULT_SUCCESS;
urUSMDeviceAlloc(.hContext = <ctx2>, .hDevice = dev0, ..., .pool = nullptr, .size = 427970304, ...)
  -> UR_RESULT_ERROR_OUT_OF_DEVICE_MEMORY;
```

Note `.pool = nullptr` on the failing call, no UR pool object is involved. The pool manager isn't even on the call path.

### Where the failure actually occurs

Tracing into NEO from the UR adapter: `urUSMDeviceAlloc` dispatches to `level_zero/core/source/context/context_imp.cpp` (`ContextImp::allocDeviceMem`). At line ~322 with our patches (pool disabled), execution falls through to:

```cpp
void *usmPtr = this->driverHandle->svmAllocsManager->createUnifiedMemoryAllocation(...);
if (usmPtr == nullptr) {
    return ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY;
}
```

`SVMAllocsManager::createUnifiedMemoryAllocation()` at `shared/source/memory_manager/unified_memory_manager.cpp:498` returns `nullptr` for multi-device contexts. The downstream call into `memoryManager->allocateGraphicsMemoryWithProperties(unifiedMemoryProperties, externalPtr)` is what fails, *not* the pool. There is a retry path via `trimUSMDeviceAllocCache()`, but it doesn't help because the failure is not a real capacity shortage.

### Suspected bisect range

After filtering out clang-format / refactor / revert noise, eight semantically meaningful commits touched `shared/source/memory_manager/unified_memory_manager.cpp` in the `25.40.35563.10..26.05.37020.3` range:

```
7c701fd69f feature:  Add multi-GPU capability for memAdvise           (Jan 19 2026)
dc0cb255c3 performance: Optimize compression condition
bb15deca7e fix: do not wait on tag when releasing in-place
dc85f33e49 fix: Disallow USM compression on peer access               (Nov 12 2025)
435c43d142 performance: Use 2MB heap for cl_buffers if possible
00ec4c82b2 fix: blocking usm reuse cleanup
6d6715bebf performance: Lock svm allocs mutex once in appendLaunchKernelWithArgs
17199556ca performance: lazy start usm reuse cleaner thread
```

`dc85f33e49` is the only one in the list that explicitly changes behavior based on multi-device peer access. Reading its diff, it disables compression rather than returning null, so it may not be directly responsible, but it touches the exact function we've isolated as the failure point. A `git bisect` between `25.40.35563.10` and `26.05.37020.3` would identify the culprit definitively.

### Stack details

- Hardware: ASRock X570 Taichi + Ryzen 5 4500, 2× Intel-reference Arc Pro B70 32 GB at PCIe 4.0 x8 each, Above 4G + ReBAR on (both cards have working 32 GB BAR2)
- Fedora 44, kernel `7.0.4-200.fc44.x86_64`, `xe` driver, GuC v70.60.0
- `intel-igc` 2.30.3, `intel-gmmlib` 22.10.0, `oneapi-level-zero` 1.28.2
- Intel oneAPI Base Toolkit 2026.0 (icpx 2026.0.0)
- Test workload: llama.cpp SYCL backend (AOT bmg_g31), Qwen3-Coder-Next 80B-A3B Q4_K_M GGUF

### Suggested updates to this issue

- The title and root-cause section currently point at the pool-manager commit `7bb2d32`. That commit reproduces the symptom **only because pool init happens early in the alloc path**; reverting it does not fix the bug. The actual failure is in `SVMAllocsManager::createUnifiedMemoryAllocation` returning null on multi-device. Maintainers may want to update the issue title/labels accordingly.
- The "Last Known Working Driver Version" field at the top is correct (`25.40.x` works). The "First Known Failing Driver Version" should probably broaden, `26.05.37020.3-1` fails, not just `26.09`. The regression is older than this issue originally suggested.

Happy to attach the full UR trace, the `LD_DEBUG=libs` log proving Ubuntu binaries fail identically, the GCC 15 patch set for building 25.40/26.05/26.14 on Fedora 44, or any other artifact useful to your team.

**Comment by Stoney49th** [comment]
do you need more info for fixing this? if required, I can provide additional debug output, just let me know what you need. I can only provide output from within a docker environment. Hardware here is 2x B50.

**Comment by jwarchul** [comment]
Hi @fradav, @david-bue, @Stoney49th,

Thank you all for reporting this. The NEO regression you're seeing was introduced by this [commit](https://github.com/intel/compute-runtime/commit/dd252e7852fcaea529286c20f8d5bde827ed91f7).

That said, this commit is not actually a regression on its own - the previous implementation was masking a real bug that lives in the Linux kernel's drm/xe driver. The underlying kernel bug has already been fixed upstream by this [commit](https://github.com/torvalds/linux/commit/609fc8766d68da10697e1df0514d079d54bf48df).

The fix is available in Linux kernel v7.1-rc1 and later, so upgrading to v7.1 (or any later release) resolves the issue at its root.

If you aren't able to upgrade your kernel yet, you can use the following NEO debug flags as a workaround:
`NEOReadDebugKeys=1 ForceZeDeviceCanAccessPerReturnValue=0`
This forces zeDeviceCanAccessPeer to always return false, which makes the runtime skip the peer-to-peer path entirely and fall back to a host-staged copy. The workload will run correctly instead of failing with OUT_OF_DEVICE_MEMORY.

Worth noting: on these affected kernels, you weren't actually getting the P2P path before the regression either. The old NEO probe exercised XE_VM_BIND end-to-end and hit the very same kernel bug, so it was already returning false, and the runtime was silently falling back to a host-staged copy.

Could you please verify whether this workaround resolves the problem on your side?

Thanks again for the report and the great collaboration!

**Comment by jwarchul** [comment]
As of https://github.com/intel/compute-runtime/commit/e91243a9d03de849f45d8b862a62afd4424cff8b, this issue should be resolved even when running on the buggy kernel (pre-7.1).

**Comment by Stoney49th** [comment]
@jwarchul thanks for taking this over and the fix! Will this land in the next 26.22 release or earlier?

**Comment by jwarchul** [comment]
@Stoney49th, the fix should land in the 26.22 release.

**Comment by jwarchul** [comment]
Hi @fradav, @david-bue, @Stoney49th,

Thank you for your patience throughout this process.

The fix has been successfully merged into the latest release, which is available at the following link:
* https://github.com/intel/compute-runtime/releases/tag/26.22.38646.4

Could you please verify if the issue is resolved on your end? Once confirmed, we will close this ticket.

Thank you for your collaboration and support.

**Comment by mjsabby** [comment]
Verified to work on 26.22.38646.4 -- we should be able to close this issue. @fradav you could close this issue.

**Comment by kgibala** [comment]
Hi @fradav,

We'd like to know if this issue is still affecting you. If possible, please retest on the release mentioned in the previous comments and let us know whether the problem still occurs. Any updates or additional details are welcome. Otherwise, we'll close this issue after 30 days of inactivity.

Your feedback is appreciated.

**Comment by david-bue** [comment]
I have just installed my third B70 GPU in my workstation and will have a chance to test it after the 3rd of August. 

I will report back when I have tested everything.

**Comment by kgibala** [comment]
Hi @david-bue / @fradav 

I hope you're doing well. Have you had a chance to retest this issue on the stack mentioned above? We'd like to confirm with you whether the problem has been resolved so that we can proceed to close this ticket.

Thank you for your cooperation.

**Comment by david-bue** [comment]
Yes, I hereby confirm that in the issue is completely gone. Intel stack as follows.

[david@archlinux ~]$ pacman -Q | grep -iE "intel|level.zero|igc|gmmlib|opencl|compute-runtime|ze"
breeze 6.7.4-1
breeze-cursors 6.7.4-1
breeze-gtk 6.7.4-1
breeze-icons 6.29.0-1
intel-compute-runtime 26.27.39122.11-1
intel-gmmlib 22.10.0-1
intel-gpu-tools 2.5-1
intel-graphics-compiler 1:2.38.2-1
intel-media-driver 26.2.4-1
intel-oneapi-toolkit 2026.0.1.27+c9c3d3e3_ddb4_490e_bb41_6e9041ba32a7-2
level-zero-headers 1.32.0-1
level-zero-loader 1.32.0-1
libbytesize 2.12-3
libva-intel-driver 2.4.5-1
linux-firmware-intel 20260810-2
qqc2-breeze-style 6.7.4-1
vulkan-intel 1:26.1.7-1
zenity 4.2.2-1
zeromq 4.3.5-3

**Comment by kgibala** [comment]
Thank you @david-bue for the verification. 

@fradav could you please also confirm that the issue is gone?

**Comment by jwarchul** [comment]
Hi @fradav,

We’d like to know if this issue is still affecting you. If so, please provide an update or any additional information. Otherwise, we’ll close this issue after 30 days of inactivity. Your feedback is appreciated.
