### ISSUE TITLE
[GSD-12694] Multi-BMG Level Zero device enumeration broken by deferred internal-engine init (regression NEO 25.40→25.44, Arc Pro B50/B60/B70)

### ISSUE THREAD

**Issue by F3zz1k** [intel/compute-runtime#921]
### Pre-submission Checklist

- [x] I am using the latest GPU driver version ([releases](https://github.com/intel/compute-runtime/releases))
- [ ] I have searched for similar issues and found none

### GPU Hardware

Intel Arc Pro B70

### DRI Devices Information

0 crw-rw----+ 1 root video  226,   0 May  2 23:05 /dev/dri/card0
0 crw-rw----+ 1 root video  226,   1 May  2 22:31 /dev/dri/card1
0 crw-rw-rw-  1 root render 226, 128 May  2 22:31 /dev/dri/renderD128
0 crw-rw-rw-  1 root render 226, 129 May  2 22:31 /dev/dri/renderD129

/dev/dri/by-path:
total 0
0 lrwxrwxrwx 1 root root  8 May  2 22:31 pci-0000:43:00.0-card -> ../card1
0 lrwxrwxrwx 1 root root 13 May  2 22:31 pci-0000:43:00.0-render -> ../renderD128
0 lrwxrwxrwx 1 root root  8 May  2 22:31 pci-0000:47:00.0-card -> ../card0
0 lrwxrwxrwx 1 root root 13 May  2 22:31 pci-0000:47:00.0-render -> ../renderD129

### GPU Detailed Information (lspci output)

47:00.0 VGA compatible controller: Intel Corporation Battlemage G31 [Intel Graphics] (prog-if 00 [VGA controller])
	Subsystem: Intel Corporation Device 1701
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0, Cache Line Size: 64 bytes
	Interrupt: pin ? routed to IRQ 60
	NUMA node: 1
	Region 0: Memory at 7e800000000 (64-bit, prefetchable) [size=16M]
	Region 2: Memory at 7e000000000 (64-bit, prefetchable) [size=32G]
	Expansion ROM at 82000000 [disabled] [size=2M]
	Capabilities: [40] Vendor Specific Information: Intel Capabilities v1
		CapA: Peg60Dis- Peg12Dis- Peg11Dis- Peg10Dis- PeLWUDis- DmiWidth=x4
		      EccDis- ForceEccEn- VTdDis- DmiG2Dis- PegG2Dis- DDRMaxSize=Unlimited
		      1NDis- CDDis- DDPCDis- X2APICEn- PDCDis- IGDis- CDID=0 CRID=0
		      DDROCCAP+ OCEn- DDRWrtVrefEn+ DDR3LEn+
		CapB: ImguDis- OCbySSKUCap- OCbySSKUEn- SMTCap- CacheSzCap 0x0
		      SoftBinCap- DDR3MaxFreqWithRef100=Disabled PegG3Dis-
		      PkgTyp- AddGfxEn- AddGfxCap- PegX16Dis- DmiG3Dis- GmmDis-
		      DDR3MaxFreq=2932MHz LPDDR3En-
	Capabilities: [70] Express (v2) Endpoint, IntMsgNum 0
		DevCap:	MaxPayload 256 bytes, PhantFunc 0, Latency L0s unlimited, L1 unlimited
			ExtTag+ AttnBtn- AttnInd- PwrInd- RBE+ FLReset+ SlotPowerLimit 0W TEE-IO-
		DevCtl:	CorrErr- NonFatalErr- FatalErr- UnsupReq-
			RlxdOrd+ ExtTag+ PhantFunc- AuxPwr- NoSnoop+ FLReset-
			MaxPayload 256 bytes, MaxReadReq 512 bytes
		DevSta:	CorrErr- NonFatalErr- FatalErr- UnsupReq- AuxPwr- TransPend-
		LnkCap:	Port #0, Speed 2.5GT/s, Width x1, ASPM L0s L1, Exit Latency L0s <64ns, L1 <1us
			ClockPM- Surprise- LLActRep- BwNot- ASPMOptComp+
		LnkCtl:	ASPM Disabled; RCB 64 bytes, LnkDisable- CommClk-
			ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt- FltModeDis-
		LnkSta:	Speed 2.5GT/s, Width x1
			TrErr- Train- SlotClk- DLActive- BWMgmt- ABWMgmt-
		DevCap2: Completion Timeout: Range B, TimeoutDis+ NROPrPrP- LTR+
			 10BitTagComp+ 10BitTagReq+ OBFF Not Supported, ExtFmt+ EETLPPrefix-
			 EmergencyPowerReduction Not Supported, EmergencyPowerReductionInit-
			 FRS- TPHComp- ExtTPHComp-
			 AtomicOpsCap: 32bit- 64bit- 128bitCAS-
		DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis-
			 AtomicOpsCtl: ReqEn-
			 IDOReq- IDOCompl- LTR- EmergencyPowerReductionReq-
			 10BitTagReq- OBFF Disabled, EETLPPrefixBlk-
		LnkCap2: Supported Link Speeds: 2.5GT/s, Crosslink- Retimer- 2Retimers- DRS-
		LnkCtl2: Target Link Speed: 2.5GT/s, EnterCompliance- SpeedDis-
			 Transmit Margin: Normal Operating Range, EnterModifiedCompliance- ComplianceSOS-
			 Compliance Preset/De-emphasis: -6dB de-emphasis, 0dB preshoot
		LnkSta2: Current De-emphasis Level: -6dB, EqualizationComplete- EqualizationPhase1-
			 EqualizationPhase2- EqualizationPhase3- LinkEqualizationRequest-
			 Retimer- 2Retimers- CrosslinkRes: unsupported, FltMode-
	Capabilities: [ac] MSI: Enable+ Count=1/1 Maskable+ 64bit+
		Address: 00000000fee1e000  Data: 0020
		Masking: 00000000  Pending: 00000000
	Capabilities: [d0] Power Management version 3
		Flags: PMEClk- DSI- D1- D2- AuxCurrent=0mA PME(D0+,D1-,D2-,D3hot+,D3cold-)
		Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
	Capabilities: [100 v1] Alternative Routing-ID Interpretation (ARI)
		ARICap:	MFVC- ACS-, Next Function: 0
		ARICtl:	MFVC- ACS-, Function Group: 0
	Capabilities: [110 v1] Null
	Capabilities: [200 v1] Address Translation Service (ATS)
		ATSCap:	Invalidate Queue Depth: 00
		ATSCtl:	Enable-, Smallest Translation Unit: 00
	Capabilities: [420 v1] Physical Resizable BAR
		BAR 2: current size: 32GB, supported: 256MB 512MB 1GB 2GB 4GB 8GB 16GB 32GB
	Capabilities: [220 v1] Virtual Resizable BAR
		BAR 2: current size: 8GB, supported: 256MB 512MB 1GB 2GB 4GB 8GB 16GB 32GB
	Capabilities: [320 v1] Single Root I/O Virtualization (SR-IOV)
		IOVCap:	Migration- 10BitTagReq+ IntMsgNum 0
		IOVCtl:	Enable- Migration- Interrupt- MSE- ARIHierarchy+ 10BitTagReq-
		IOVSta:	Migration-
		Initial VFs: 4, Total VFs: 4, Number of VFs: 0, Function Dependency Link: 00
		VF offset: 1, stride: 1, Device ID: e223
		Supported Page Size: 00000553, System Page Size: 00000001
		Region 0: Memory at 0000000000000000 (64-bit, prefetchable)
		Region 2: Memory at 0000000000000000 (64-bit, prefetchable)
		VF Migration: offset: 00000000, BIR: 0
	Capabilities: [400 v1] Latency Tolerance Reporting
		Max snoop latency: 0ns
		Max no snoop latency: 0ns
	Kernel driver in use: xe
	Kernel modules: xe

43:00.0 VGA compatible controller: Intel Corporation Battlemage G31 [Intel Graphics] (prog-if 00 [VGA controller])
	Subsystem: Intel Corporation Device 1701
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0, Cache Line Size: 64 bytes
	Interrupt: pin ? routed to IRQ 58
	NUMA node: 1
	Region 0: Memory at 7f800000000 (64-bit, prefetchable) [size=16M]
	Region 2: Memory at 7f000000000 (64-bit, prefetchable) [size=32G]
	Expansion ROM at 82400000 [disabled] [size=2M]
	Capabilities: [40] Vendor Specific Information: Intel Capabilities v1
		CapA: Peg60Dis- Peg12Dis- Peg11Dis- Peg10Dis- PeLWUDis- DmiWidth=x4
		      EccDis- ForceEccEn- VTdDis- DmiG2Dis- PegG2Dis- DDRMaxSize=Unlimited
		      1NDis- CDDis- DDPCDis- X2APICEn- PDCDis- IGDis- CDID=0 CRID=0
		      DDROCCAP+ OCEn- DDRWrtVrefEn+ DDR3LEn+
		CapB: ImguDis- OCbySSKUCap- OCbySSKUEn- SMTCap- CacheSzCap 0x0
		      SoftBinCap- DDR3MaxFreqWithRef100=Disabled PegG3Dis-
		      PkgTyp- AddGfxEn- AddGfxCap- PegX16Dis- DmiG3Dis- GmmDis-
		      DDR3MaxFreq=2932MHz LPDDR3En-
	Capabilities: [70] Express (v2) Endpoint, IntMsgNum 0
		DevCap:	MaxPayload 256 bytes, PhantFunc 0, Latency L0s unlimited, L1 unlimited
			ExtTag+ AttnBtn- AttnInd- PwrInd- RBE+ FLReset+ SlotPowerLimit 0W TEE-IO-
		DevCtl:	CorrErr- NonFatalErr- FatalErr- UnsupReq-
			RlxdOrd+ ExtTag+ PhantFunc- AuxPwr- NoSnoop+ FLReset-
			MaxPayload 256 bytes, MaxReadReq 512 bytes
		DevSta:	CorrErr- NonFatalErr- FatalErr- UnsupReq- AuxPwr- TransPend-
		LnkCap:	Port #0, Speed 2.5GT/s, Width x1, ASPM L0s L1, Exit Latency L0s <64ns, L1 <1us
			ClockPM- Surprise- LLActRep- BwNot- ASPMOptComp+
		LnkCtl:	ASPM Disabled; RCB 64 bytes, LnkDisable- CommClk-
			ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt- FltModeDis-
		LnkSta:	Speed 2.5GT/s, Width x1
			TrErr- Train- SlotClk- DLActive- BWMgmt- ABWMgmt-
		DevCap2: Completion Timeout: Range B, TimeoutDis+ NROPrPrP- LTR+
			 10BitTagComp+ 10BitTagReq+ OBFF Not Supported, ExtFmt+ EETLPPrefix-
			 EmergencyPowerReduction Not Supported, EmergencyPowerReductionInit-
			 FRS- TPHComp- ExtTPHComp-
			 AtomicOpsCap: 32bit- 64bit- 128bitCAS-
		DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis-
			 AtomicOpsCtl: ReqEn-
			 IDOReq- IDOCompl- LTR- EmergencyPowerReductionReq-
			 10BitTagReq- OBFF Disabled, EETLPPrefixBlk-
		LnkCap2: Supported Link Speeds: 2.5GT/s, Crosslink- Retimer- 2Retimers- DRS-
		LnkCtl2: Target Link Speed: 2.5GT/s, EnterCompliance- SpeedDis-
			 Transmit Margin: Normal Operating Range, EnterModifiedCompliance- ComplianceSOS-
			 Compliance Preset/De-emphasis: -6dB de-emphasis, 0dB preshoot
		LnkSta2: Current De-emphasis Level: -6dB, EqualizationComplete- EqualizationPhase1-
			 EqualizationPhase2- EqualizationPhase3- LinkEqualizationRequest-
			 Retimer- 2Retimers- CrosslinkRes: unsupported, FltMode-
	Capabilities: [ac] MSI: Enable+ Count=1/1 Maskable+ 64bit+
		Address: 00000000fee1c000  Data: 0020
		Masking: 00000000  Pending: 00000000
	Capabilities: [d0] Power Management version 3
		Flags: PMEClk- DSI- D1- D2- AuxCurrent=0mA PME(D0+,D1-,D2-,D3hot+,D3cold-)
		Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
	Capabilities: [100 v1] Alternative Routing-ID Interpretation (ARI)
		ARICap:	MFVC- ACS-, Next Function: 0
		ARICtl:	MFVC- ACS-, Function Group: 0
	Capabilities: [110 v1] Null
	Capabilities: [200 v1] Address Translation Service (ATS)
		ATSCap:	Invalidate Queue Depth: 00
		ATSCtl:	Enable-, Smallest Translation Unit: 00
	Capabilities: [420 v1] Physical Resizable BAR
		BAR 2: current size: 32GB, supported: 256MB 512MB 1GB 2GB 4GB 8GB 16GB 32GB
	Capabilities: [220 v1] Virtual Resizable BAR
		BAR 2: current size: 8GB, supported: 256MB 512MB 1GB 2GB 4GB 8GB 16GB 32GB
	Capabilities: [320 v1] Single Root I/O Virtualization (SR-IOV)
		IOVCap:	Migration- 10BitTagReq+ IntMsgNum 0
		IOVCtl:	Enable- Migration- Interrupt- MSE- ARIHierarchy+ 10BitTagReq-
		IOVSta:	Migration-
		Initial VFs: 4, Total VFs: 4, Number of VFs: 0, Function Dependency Link: 00
		VF offset: 1, stride: 1, Device ID: e223
		Supported Page Size: 00000553, System Page Size: 00000001
		Region 0: Memory at 0000000000000000 (64-bit, prefetchable)
		Region 2: Memory at 0000000000000000 (64-bit, prefetchable)
		VF Migration: offset: 00000000, BIR: 0
	Capabilities: [400 v1] Latency Tolerance Reporting
		Max snoop latency: 0ns
		Max no snoop latency: 0ns
	Kernel driver in use: xe
	Kernel modules: xe

### Driver Version

26.05.37020.3-2

### Driver Installation Details

**Kernel driver (`xe`):** ships in-kernel with Linux 6.19. Installed via Manjaro's kernel manager:    
  ```bash                                        
  sudo mhwd-kernel -i linux619                                                                          
  # Reboot, select 6.19 from GRUB                                                                       
   
  Userspace runtime + Level Zero (Manjaro official extra repo, Arch packages):                          
  sudo pacman -S intel-compute-runtime level-zero-loader vulkan-intel \                               
                 intel-media-driver intel-gpu-tools linux-firmware                                      
                                                                                                      
  Resulting versions:

│                         Package                         │     Version      │
│ intel-compute-runtime (NEO)                             │ 26.05.37020.3-2  │
│ level-zero-loader                                       │ 1.27.0-2         │
│ vulkan-intel (Mesa)                                     │ 26.0.2-1         │
│ linux-firmware-meta (incl. bmg_guc_70.bin, bmg_huc.bin) │ 20260309-1       │
│ linux619 kernel                                         │ 6.19.8-1-MANJARO │
           
                                                                                                      
  oneAPI toolkit: installed via Intel's official offline installer (not the Arch package, which is stuck
   at 2025.0.4):
  cd /tmp                                                                                               
  wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/99f4837a-25b7-425d-a897-60af022676ea/
  intel-oneapi-base-toolkit-2025.3.2.21_offline.sh                                                      
  sudo sh intel-oneapi-base-toolkit-2025.3.2.21_offline.sh -a --silent --cli --eula accept              
  - Installed to /opt/intel/oneapi/2025.3/ (alongside an earlier 2025.0/ from pacman -S   
  intel-oneapi-basekit)                                                                                 
  - Activated per-shell via source /opt/intel/oneapi/setvars.sh (setvars.sh auto-resolves latest →      
  2025.3)                                                                                               
  - which icpx → /opt/intel/oneapi/compiler/2025.3/bin/icpx (version 2025.3.3.20260319)                 
                                                                                                      
  Verification after install:                                                                           
  $ uname -r                                                                                          
  6.19.8-1-MANJARO                                                                                      
                                                                                                        
  $ lspci -k | grep -A1 -i battlemage
  0000:43:00.0 VGA compatible controller: Intel Corporation Battlemage G31 [Intel Graphics]             
      Kernel driver in use: xe                                                                        
  0000:47:00.0 VGA compatible controller: Intel Corporation Battlemage G31 [Intel Graphics]             
      Kernel driver in use: xe                                                                        
                                                                                                        
  $ sycl-ls                                                                                             
  [level_zero:gpu][level_zero:0] Intel(R) oneAPI Unified Runtime over Level-Zero V2, Intel(R) Graphics  
  [0xe223] 20.2.0 [1.14.37020]                                                                          
  [level_zero:gpu][level_zero:1] Intel(R) oneAPI Unified Runtime over Level-Zero V2, Intel(R) Graphics  
  [0xe223] 20.2.0 [1.14.37020]                                                                        
                                                                                                        
  No PPAs, custom builds, or out-of-tree modules. No DKMS. Stock Manjaro repos for the KMD/NEO/loader 
  stack + Intel's official offline installer for oneAPI 2025.3.                                         
  ```                                                  

### Linux Distribution

Arch Linux

### Kernel Version & Boot Parameters

6.19.8-1-MANJARO

BOOT_IMAGE=/@/boot/vmlinuz-6.19-x86_64 root=UUID=3c85b363-532c-4253-bf74-194699d38c4e rw rootflags=subvol=@ quiet splash apparmor=1 security=apparmor udev.log_priority=3

xe                   4222976  59
intel_vsec             28672  2 pmt_telemetry,xe
drm_ttm_helper         20480  1 xe
ttm                   126976  2 drm_ttm_helper,xe
i2c_algo_bit           24576  2 igb,xe
drm_suballoc_helper    16384  1 xe
drm_buddy              32768  1 xe
video                  81920  1 xe
gpu_sched              69632  1 xe
drm_gpuvm              57344  1 xe
drm_exec               12288  2 drm_gpuvm,xe
drm_gpusvm_helper      40960  1 xe
drm_display_helper    286720  1 xe
cec                    98304  2 drm_display_helper,xe

### Actual Behavior

  Constructing a SYCL Level Zero context that spans both discrete Arc Pro B70 GPUs throws               
  `UR_RESULT_ERROR_UNKNOWN` (2147483646) and terminates. Single-device context construction succeeds,   
  and `sycl-ls` enumerates both cards correctly. Symptom shape matches #916 (regression in NEO 26.x for 
  multi-device L0 contexts), but on Battlemage with a different error code, suggesting failure happens  
  earlier — during `urContextCreate` itself rather than first USM allocation. Cross-reference:        
  intel/llm-scaler#382 (same hardware, downstream symptom inside the Intel-published `llm-scaler-vllm`
  container).

  sycl::_V1::exception: level_zero backend failed with error: 2147483646 (UR_RESULT_ERROR_UNKNOWN)    
    sycl::_V1::context::context(std::vectorsycl::device, ...)                                           
    +0x32f783 (throw site, libsycl.so.8)                     
    std::terminate                                                                                      
                                                                                                        
  UR_LOADER_DEBUG=1 trace shows both adapters load and `libze_intel_gpu.so.1` loads; **no `zeDevice*` or
   `zeContext*` calls appear in the trace before the abort** — failure occurs inside the v2 adapter's   
  `urContextCreate` path before it issues a Level Zero call.                                            
                                                                                                        
  [INFO]: loaded adapter (libur_adapter_level_zero.so.0)    from .../libur_adapter_level_zero.so.0      
  [INFO]: loaded adapter (libur_adapter_level_zero_v2.so.0) from .../libur_adapter_level_zero_v2.so.0
  zeInit with flags value of 1                                                                          
  [ze_loader] Loader Version 1.27.0                                                                   
  [ze_loader] Loading Driver libze_intel_gpu.so.1 succeeded                                             
  [crash] 

### Expected Behavior

  Multi-device context constructs without error; subsequent allocations / queues work, as `sycl-ls`   
  already shows both devices are valid.

### Reproduction Rate

Always reproduces - 100%

### Steps to Reproduce

  1. Build llama.cpp with the SYCL backend (commit `d05fe1d` or newer).                                 
  2. With both B70s visible to the runtime, run `./llama-ls-sycl-device`.                               
  3. (Equivalent) inside `intel/llm-scaler-vllm:latest`, run `python -c "import torch;                  
  torch.xpu.device_count()"`.                                                                           
  4. (Equivalent, minimal) construct `sycl::context(std::vector<sycl::device>{dev0, dev1})` from any    
  SYCL hello-world.  

### Is this a regression?

- [ ] Yes, this is a regression - functionality that previously worked is now broken

## Workarounds tried that do NOT help (all crash identically)                                       
                                                                                                        
  | Variable / change | Effect |                                                                      
  |---|---|                                                                                             
  | `ZE_P2P_DISABLE=1` | no change |                                                                  
  | `VLLM_SKIP_P2P_CHECK=1` | no change |                                                               
  | `NEOReadDebugKeys=1 CreateMultipleRootDevices=2` | no change |                                      
  | `ONEAPI_DEVICE_SELECTOR=*:*` | no change |                                                          
  | `ZE_FLAT_DEVICE_HIERARCHY={FLAT,COMPOSITE,COMBINED}` | no change |                                  
  | `UR_LOADER_USE_LEVEL_ZERO_V2=0` | not recognised by loader |                                        
  | `UR_L0_ADAPTER_VERSION=1` | not recognised |                                                        
  | `SYCL_UR_USE_LEVEL_ZERO_V2=0` | no change (still crashes via v2 path) |                             
  | IOMMU disabled in BIOS | no change |                                                                
  | Move card to different PCIe slot (NUMA + IOMMU groups change) | no change |                         
  | All of the above combined | no change |                                                             
                                                                                                      
  ## Single-device workaround that works                                                                
  `ONEAPI_DEVICE_SELECTOR=level_zero:0` — application sees one card, no multi-device context          
  constructed, runs cleanly. Identical workaround to #916.                                              
                                                                                                      
  ## Notes                                                                                              
  - Same crash reproduces inside the Intel-published `intel/llm-scaler-vllm:latest` container, so it is
  not local environment contamination — see also intel/llm-scaler#382                                   
  (`UR_RESULT_ERROR_OUT_OF_RESOURCES` on the same 2×B70 setup, plausibly the same root cause surfacing
  one call later).                                                                                      
  - Pattern (single-device OK, `ONEAPI_DEVICE_SELECTOR=level_zero:0` works, broke in 26.x) matches    
  **intel/compute-runtime#916** (2× Arc A770), but the error code here is `UR_RESULT_ERROR_UNKNOWN`     
  rather than `OUT_OF_DEVICE_MEMORY`, suggesting the failure is in `urContextCreate` itself on
  Battlemage, before the first USM allocation that #916 fails on.                                       
  - oneAPI 2025.0.4 (Arch repo `intel-oneapi-basekit`) does **not** crash, because that release ships 
  only the v1 UR L0 adapter — strongly implicating the v2 adapter / NEO multi-device-context path. (A   
  binary built against 2025.3 against the 2025.0.4 v1 adapter has its own ABI mismatch in the alloc
  path; not requesting that be fixed, just noting.)                                                     
  - `SYCL_UR_USE_LEVEL_ZERO_V2=0` does not fall back to the v1 adapter on Xe2 — the v2 adapter is     
  selected unconditionally on BMG. If a real fallback knob exists, documenting it would itself be a
  workaround.

  ## Ask                                                                                                
  - Confirm whether this is the same root cause as #916 (NEO 26.x multi-device L0 context regression) or
   a distinct Battlemage path.                                                                          
  - If it is #916, please link / dup. If distinct, a NEO debug knob to bypass the v2-adapter          
  multi-device codepath on BMG would unblock dual-B70 vLLM users today.

**Comment by ClancyBuf** [comment]
Summary

I am seeing a regression with two Intel Arc Pro B60 GPUs on Fedora 43.

With the Fedora 43 Intel GPU runtime stack at 26.09.37435.12-4.fc43, each GPU works individually when selected with ZE_AFFINITY_MASK=0 or ZE_AFFINITY_MASK=1, but exposing both GPUs together with ZE_AFFINITY_MASK=0,1 causes PyTorch XPU device enumeration to fail inside:

torch._C._xpu_getDeviceCount()

The failure is:

RuntimeError: level_zero backend failed with error: 2147483646 (UR_RESULT_ERROR_UNKNOWN)

Downgrading the Intel GPU runtime stack to 25.31.34666.3-1.fc43 fixes dual-device enumeration: torch._C._xpu_getDeviceCount() returns 2.

Hardware

Two Intel Arc Pro B60 GPUs.

Both appear in sysfs:

/sys/class/drm/renderD128/device
vendor: 0x8086
device: 0xe211
driver: /sys/bus/pci/drivers/xe

/sys/class/drm/renderD129/device
vendor: 0x8086
device: 0xe211
driver: /sys/bus/pci/drivers/xe

OS / environment

Fedora 43 container on Fedora host, using Intel Arc Pro B60 GPUs passed through.

Kernel driver:

xe

Python environment:

Python: 3.12
torch: 2.11.0+xpu

Also reproduced with:

torch: 2.13.0.dev20260503+xpu

Broken package versions

Dual-GPU enumeration fails with:

intel-compute-runtime-26.09.37435.12-4.fc43.x86_64
intel-level-zero-26.09.37435.12-4.fc43.x86_64
intel-level-zero-devel-26.09.37435.12-4.fc43.x86_64
intel-opencl-26.09.37435.12-4.fc43.x86_64
intel-ocloc-26.09.37435.12-4.fc43.x86_64
intel-gmmlib-22.9.0-1.fc43.x86_64
intel-igc-2.30.3-1.fc43.x86_64
intel-igc-libs-2.30.3-1.fc43.x86_64

Working package versions

Dual-GPU enumeration works after downgrading to:

intel-compute-runtime-25.31.34666.3-1.fc43.x86_64
intel-level-zero-25.31.34666.3-1.fc43.x86_64
intel-level-zero-devel-25.31.34666.3-1.fc43.x86_64
intel-opencl-25.31.34666.3-1.fc43.x86_64
intel-ocloc-25.31.34666.3-1.fc43.x86_64
intel-gmmlib-22.8.2-1.fc43.x86_64
intel-igc-2.16.0-1.fc43.x86_64
intel-igc-libs-2.16.0-1.fc43.x86_64

Reproducer

Single GPU 0 works:

source /opt/vllm-xpu/bin/activate

unset SYCL_DEVICE_FILTER
unset ZE_ENABLE_ALT_DRIVERS
unset ZE_FLAT_DEVICE_HIERARCHY

export ONEAPI_DEVICE_SELECTOR=level_zero:gpu
export ZE_AFFINITY_MASK=0

python - <<'PY'
import torch, os
print("ZE_AFFINITY_MASK:", os.environ.get("ZE_AFFINITY_MASK"))
print("torch:", torch.version)
print("xpu available:", torch.xpu.is_available())
print("xpu count:", torch.xpu.device_count())
for i in range(torch.xpu.device_count()):
torch.xpu.set_device(i)
print(i, torch.xpu.get_device_name(i))
PY

Output:

ZE_AFFINITY_MASK: 0
torch: 2.11.0+xpu
xpu available: True
xpu count: 1
0 Intel(R) Arc(TM) Pro B60 Graphics

Single GPU 1 works:

export ZE_AFFINITY_MASK=1

python - <<'PY'
import torch, os
print("ZE_AFFINITY_MASK:", os.environ.get("ZE_AFFINITY_MASK"))
print("torch:", torch.version)
print("xpu available:", torch.xpu.is_available())
print("xpu count:", torch.xpu.device_count())
for i in range(torch.xpu.device_count()):
torch.xpu.set_device(i)
print(i, torch.xpu.get_device_name(i))
PY

Output:

ZE_AFFINITY_MASK: 1
torch: 2.11.0+xpu
xpu available: True
xpu count: 1
0 Intel(R) Arc(TM) Pro B60 Graphics

Both GPUs fail on 26.09:

export ZE_AFFINITY_MASK=0,1

python - <<'PY'
import torch, os, traceback
print("ZE_AFFINITY_MASK:", os.environ.get("ZE_AFFINITY_MASK"))
print("torch:", torch.version)
print("calling torch._C._xpu_getDeviceCount()")
try:
print("count:", torch._C._xpu_getDeviceCount())
except Exception:
traceback.print_exc()
PY

Output on 26.09.37435.12:

ZE_AFFINITY_MASK: 0,1
torch: 2.11.0+xpu
calling torch._C._xpu_getDeviceCount()
RuntimeError: level_zero backend failed with error: 2147483646 (UR_RESULT_ERROR_UNKNOWN)

Both GPUs work on 25.31:

After downgrading to the 25.31.34666.3 package set:

export ZE_AFFINITY_MASK=0,1
export ONEAPI_DEVICE_SELECTOR=level_zero:gpu

python - <<'PY'
import torch
print("torch:", torch.version)
print("count:", torch._C._xpu_getDeviceCount())
for i in range(torch.xpu.device_count()):
print(i, torch.xpu.get_device_name(i))
PY

Output:

torch: 2.11.0+xpu
count: 2
0 Intel(R) Arc(TM) Pro B60 Graphics
1 Intel(R) Arc(TM) Pro B60 Graphics

Native Level Zero device enumeration

A small C Level Zero test using zeInit, zeDriverGet, zeDeviceGet, and zeDeviceGetProperties can see both devices successfully even when ZE_AFFINITY_MASK=0,1:

zeInit: ZE_RESULT_SUCCESS
zeDriverGet count: 1
Driver 0 zeDeviceGet count: 2

Device 0:
name: Intel(R) Arc(TM) Pro B60 Graphics
deviceId: 0xe211
uuid includes PCI/device marker ... 0c ...

Device 1:
name: Intel(R) Arc(TM) Pro B60 Graphics
deviceId: 0xe211
uuid includes PCI/device marker ... 45 ...

So basic Level Zero enumeration appears to work, but the PyTorch/SYCL/UR path fails when creating or initializing the two-device context on 26.09.

Notes

The failure is not that either card is bad. Each card works individually.

This appears to be a regression between:

25.31.34666.3 -> works with two B60s
26.09.37435.12 -> fails with two B60s

Please let me know if this should instead be filed against the Unified Runtime / Intel LLVM SYCL stack. I am filing here first because the behavior tracks the intel-compute-runtime / intel-level-zero package version.

**Comment by F3zz1k** [comment]
Can confirm, the regression is between NEO 25.40 and 25.48.

**Comment by ClancyBuf** [comment]
25.44 changed BMG internal engine/context initialization from eager to deferred.
This may have caused Level Zero device creation/enumeration to fail in multi-BMG systems because an internal BCS context was not initialized early enough.

**Comment by ClancyBuf** [comment]
I think the multi-GPU enumeration regression may be related to the BMG internal engine/context initialization changes between 25.40.35563.4 and 25.44.36015.5.

Working version:
- intel-compute-runtime / intel-level-zero 25.40.35563.4

Broken version:
- intel-compute-runtime / intel-level-zero 25.44.36015.5 / 25.44.36015.8

Observed behaviour:
- System has two Intel BMG discrete GPUs.
- Older runtime enumerates both GPUs correctly.
- Newer 25.44 runtime does not enumerate both GPUs correctly.
- This appears before vLLM/oneCCL involvement, so it looks like a Level Zero / compute-runtime device discovery or device initialization issue.

Suspicious change:
Commit cf3f5d74994a2aaa9dc728f4a8b8c32ab7bec78b

Title:
performance: defer internal context init, ptl, bmg

This added/changed BMG/PTL product-helper behaviour so that internal engine initialization is deferred:

    bool ProductHelperHw<gfxProduct>::initializeInternalEngineImmediately() const {
        return false;
    }

For BMG this is in:

    shared/source/xe2_hpg_core/bmg/os_agnostic_product_helper_bmg.inl

For PTL this is in:

    shared/source/xe3_core/ptl/os_agnostic_product_helper_ptl.inl

The likely behavioural change is:

Before:
- Internal engines/contexts were initialized immediately during device setup unless otherwise overridden.

After:
- BMG/PTL explicitly defer internal engine/context initialization.

There is also a follow-up commit that looks directly related:

Commit a673c5deeab3c907f0c253e37ac08dffb614b92d

Title:
fix: always initialize internal bcs engine

This changed OsContext::isImmediateContextInitializationEnabled() from effectively:

    if (engineUsage == EngineUsage::internal) {
        return initializeInternalEngineImmediately;
    }

to:

    if (engineUsage == EngineUsage::internal) {
        return initializeInternalEngineImmediately || engineType == aub_stream::EngineType::ENGINE_BCS;
    }

File:

    shared/source/os_interface/os_context.cpp

That follow-up suggests the original deferred-initialization change may have deferred too much, and that internal BCS still needs to be initialized eagerly.

My theory:
- The 25.44 runtime changed BMG internal engine/context initialization from eager to deferred.
- In a multi-BMG system, the Level Zero device creation/enumeration path may still rely on an internal BCS/context being available during early device setup.
- As a result, the second GPU may fail initialization or be skipped during enumeration.
- The later “always initialize internal bcs engine” fix looks like it may be addressing exactly this class of fallout.

Suggested thing to check:
- Does 25.44.36015.5 / 25.44.36015.8 include the BMG deferred internal context init change without the correct internal BCS eager-init behaviour?
- If so, can the BCS eager-init fix be backported to the affected 25.44 package?
- Alternatively, can BMG temporarily revert initializeInternalEngineImmediately() to true to confirm whether enumeration recovers?

Minimal test patch idea:

    if (engineUsage == EngineUsage::internal) {
        return initializeInternalEngineImmediately || engineType == aub_stream::EngineType::ENGINE_BCS;
    }

in:

    shared/source/os_interface/os_context.cpp

If that restores enumeration of both BMG GPUs, it would strongly indicate the regression is caused by the deferred internal context/engine initialization change rather than PCIe topology, vLLM, or oneCCL.

**Comment by ClancyBuf** [comment]
After forcing BMG initializeInternalEngineImmediately() back to true and rebuilding compute-runtime 26.09.37435.12, both B60 GPUs enumerate and zeDeviceCanAccessPeer() reports peer access in both directions:

Drivers: 1
Driver 0 devices: 2
Device 0: Intel(R) Arc(TM) Pro B60 Graphics device=0xe211
Device 1: Intel(R) Arc(TM) Pro B60 Graphics device=0xe211
P2P 0 -> 1: ze_result=0x0 canAccess=1
P2P 1 -> 0: ze_result=0x0 canAccess=1

The only source change was:

shared/source/xe2_hpg_core/bmg/os_agnostic_product_helper_bmg.inl

ProductHelperHw<gfxProduct>::initializeInternalEngineImmediately()

from:
    return false;

to:
    return true;

This confirms the regression is tied to the BMG deferred internal engine/context initialization path, and not to PCIe topology or Level Zero P2P capability on this system.

**Comment by F3zz1k** [comment]
I've got claude opus trying to build and test, so far we got it enumerating but not running:

  Hardware: 4× Intel Arc Pro B70 (BMG, device id 0xe223), Threadripper 1950X, Arch Linux                
  Software stack tested with the one-line patch applied                                               
  (initializeInternalEngineImmediately() false→true):                                                   
                                                                                                      
    compute-runtime    igc           result                                                             
    ---------------    ----------    -----------------------------------------                        
    26.05.37020.3      2.32.7        Built OK (skip-unit-tests). All SYCL                               
                                     workloads crash with                      
                                     UR_RESULT_ERROR_UNKNOWN even on a single                           
                                     device. llama-server --list-devices throws                        
                                     the exception from sycl::context().                                
    26.14.37833.4      2.32.7        Built OK. Same crash as 26.05 on single                            
                                     and multi-device workloads.                                        
    26.14 + UR_LOADER_USE_LEVEL_ZERO_V2=0                                                               
                       2.32.7        Devices enumerate cleanly (sycl-ls and                             
                                     llama-server --list-devices both report   
                                     4×Arc, ~32 GB free each), BUT model load                           
                                     dies at buffer alloc:                                            
                                       llama_model_load: error loading model:                           
                                       unable to allocate SYCL3 buffer                                  
    26.18.38308.1      2.32.7        Won't compile — references IGFX_NVL                                
                                     (Nova Lake) which 2.32.7 doesn't define.                           
                                     Need igc ≥2.33. Will try updating.                                                    
                                                                                                        
  25.40.35563.4 (the previously-recommended pin) is still the only version that                         
  works in production on this rig. The patch is necessary but not                                 
  sufficient on 26.05/26.14/26.18 — a separate GPU-memory regression appears                          
  to be tripping buffer allocation even with the L0 V2 loader disabled.

**Comment by F3zz1k** [comment]
One-line patch unblocks device enumeration but every 26.x compute-runtime we can build against the available igc (2.32.7 or 2.34.4-bin) still hits a separate buffer-allocation regression (unable to allocate SYCL buffer / ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY) that the patch doesn't fix and 26.18 (which has plausibly-relevant fixes for that allocation bug in its commit log) won't compile because it references IGFX_NVL, a symbol only present in igc ≥ 2.35 which isn't packaged for Arch yet.
I've never built IGC before but I'll attempt it and see if it changes anything.

**Comment by F3zz1k** [comment]
4× Intel Arc Pro B70 (BMG-G31, 0xe223), Arch Linux + oneAPI 2025.3. Tried ~14 build combinations of compute-runtime 26.05 / 26.09 / 26.14 / 26.18, with the BMG initializeInternalEngineImmediately() one-line patch, with and without intel-graphics-compiler 2.35.2 built from source (clang+libc++) and intel-gmmlib's igfxfmid.h patched to define IGFX_NVL. Every 26.x driver either fails to compile, crashes at `sycl-ls`, or aborts at runtime in `shared/source/gmm_helper/client_context/gmm_client_context.cpp:50` (ABI mismatch between compute-runtime built against the patched IGFX enum and the installed libgmm.so built without it). The BMG one-liner is necessary but not sufficient — david-bue's SVMAllocsManager::createUnifiedMemoryAllocatiofinding on #916 matches our observations exactly. 25.40.35563.4-4 remains the only working pin on this hardware. Endorsing bisect of dc85f33e49 ("fix: Disallow USM compression on peer access", NEO-15427) as the prime suspect.

**Comment by F3zz1k** [comment]
● 4× Arc Pro B70 on 26.05.37020.3 (Manjaro, kernel 7.0.3, xe driver): multi-device sycl::context        
  construction still throws UR_RESULT_ERROR_UNKNOWN even after reverting dc85f33e49 ("Disallow USM
  compression on peer access") — single-device L0 works fine, so the regression is upstream of          
  SVMAllocsManager. 

I don't think there's anything else I can do.   Sticking to intel-compute-runtime 25.40.35563.10-1 until B70 support is fixed.

**Comment by Stoney49th** [comment]
Same here as well. And thanks for all the info regarding the last working version before it broke. Really a good hint on how to make llama.cpp work again. Is this beeing looked at already? What is the planned timeline for a fix?

**Comment by F3zz1k** [comment]
@Stoney49th I don't think anyone is actively looking at fixing this yet.  Seems Arc Pro is low priority (few people have them) and I'm not familiar enough with this platform to contribute a fix.  We will probably have to wait for someone at intel to get involved.

**Comment by F3zz1k** [comment]
I let an AI hack at it all day.  Dropping here in case it's useful..  TLDR: seems to be a xe kernel driver bug and likely not something we can fully fix here.  It does propose a partial fix for compute-runtime which would at least get single card working but I'll leave it here as is until the devs get a chance to look at it. 

<details>
  <summary>Click to expand</summary>
  
# compute-runtime#921 — full diagnosis after on-rig instrumentation

Hardware: 4× Intel Arc Pro B70 (BMG, xe2_hpg_core, device 0xe223), xe kernel driver, Manjaro 7.0.3.

## Bug, restated precisely

When multiple BMG devices are exposed to a single process, `sycl::context(vector<device>)` throws `UR_RESULT_ERROR_UNKNOWN`. Same for any tool that triggers multi-device UR context construction (`llama-ls-sycl-device`, `llama-cli --list-devices` with both cards, vLLM with `tensor_parallel_size>1`, etc.).

## The actual root cause

The xe kernel driver rejects `DRM_IOCTL_XE_VM_BIND` with **`EINVAL` (22)** when binding a peer-imported (DMA-buf imported from another BMG device) buffer object to the peer device's VM. This happens **on every engine on the peer device** — CCS, BCS, all of them. The bind fails regardless of engine type or `vmBindFlags`.

Captured from the rig with printf instrumentation in compute-runtime:

```
bind BO-33 to VM 1, vmHandleId = 0,
range: ffffc001ffc20000 - ffffc001ffc30000, size: 65536,
result: -1, errno: 22 (Invalid argument)
```

This means: when compute-runtime's peer-import (`getPeerAllocation` → `importFdHandle` → `createGraphicsAllocationFromSharedHandle`) gives the kernel a DMA-buf FD from device 0 and asks the kernel to bind it into device 1's VM at the same GPU VA as the source, the kernel says no. compute-runtime has done its part correctly — the FD is valid, the GEM handle on the peer device is valid, the VA range is valid (size, alignment, no overlap). The kernel just won't bind it.

This is a kernel-side limitation of the xe driver shipped with Manjaro 7.0.3. It's outside compute-runtime's reach to fully fix.

## How the symptom escalates to `UR_RESULT_ERROR_UNKNOWN`

1. SYCL `sycl::context(vector<device>)` → UR `urContextCreate`. The V2 UR adapter (default for BMG IP version 20.2.0) decides to allocate a 1-byte device USM on device 0 and then call `zeContextMakeMemoryResident(device_1, ptr, size)` to mirror it onto every peer device in the context — that's its "validate the multi-device context is usable" handshake.
2. compute-runtime `Context::makeMemoryResident(device_1, ptr, size)`:
   - `getDriverSystemMemoryAllocation(ptr, size, root=1)` returns `nullptr` (alloc isn't tracked on device 1)
   - falls through to `findAllocationDataForRange` + `getPeerAllocation(device_1, allocData, ptr, ...)`
   - `getPeerAllocation` peer-imports the source FD to device 1 via `peekInternalHandle` → `importFdHandle(neoDevice_1, basePointer=src_VA)` — succeeds, returns the peer-mapped GraphicsAllocation
   - then `memoryOperationsIface->makeResident(neoDevice_1, peerAlloc, true, true)` iterates `device_1->getAllEngines()` and calls `bo->bind` for each
3. The very first `bo->bind` (or any subsequent one) hits the EINVAL from xe and `DrmMemoryOperationsHandlerBind::makeResidentWithinOsContext` returns `MemoryOperationsStatus::outOfMemory`
4. `Context::makeMemoryResident` maps that to `ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY (0x70000003)`
5. The V2 UR adapter propagates as `UR_RESULT_ERROR_UNKNOWN (2147483646)` from `urContextCreate`
6. SYCL throws.

The V1 adapter doesn't take this path during context construction — it ignores residency failures and trusts that residency will be established lazily. That's why "V1 enumerates fine" was a misleading data point in the #921 thread: V1 doesn't actually run cross-device anything either; it just doesn't fail at construction time. Once you `malloc_device` and try to use it cross-device on V1, it also throws — confirmed on the rig.

## Why prior hypotheses didn't hold up

| Hypothesis | What rig instrumentation showed |
|---|---|
| Deferred internal engine init on BMG (`cf3f5d7499`) — fix by setting `initializeInternalEngineImmediately() = true` | Necessary but unrelated to the multi-device bug. Without the patch, even single-device init has issues; with the patch, single-device works. The multi-device bug is downstream of this. ClancyBuf's 2×B60 success is a stronger reproducer than B70 because B60 may have different kernel-side acceptance — but on 4×B70 the patch alone is insufficient. |
| `dc85f33e49` USM-compression-on-peer-access regression — fix by reverting | Reverting actually makes things worse (forces compressed=1 on the peer-probe allocation). On the production `compute-runtime-26.05.37020.3 + BMG one-liner + dc85f33e49 revert` build, instrumentation shows `compressed=1` going into the peer bind. Restoring `dc85f33e49` makes the alloc go in with `compressed=0` (correct), but the kernel still rejects the bind. The revert in `~/build/compute-runtime-pkg/020-revert-dc85f33e49-usm-compression-peer-access.patch` should be dropped. |
| Bind eventually succeeds later in the trace — fix by retry | The "later success" is a different GEM handle that happens to reuse the same BO number. With the permissive variant (continue past failures, no early break in `DrmMemoryOperationsHandlerBind::makeResident`), all 5 engines on the peer device fail with EINVAL — not engine-specific. |
| Internal-RCS context still deferred | Wrong premise. BMG's default engine type is CCS, not RCS. The internal-default-engine context that stays deferred on BMG is internal-CCS, which `initializeResources(false, ...)` explicitly initializes inside `DrmMemoryOperationsHandlerBind::makeResident` before each bind attempt. Engine init isn't the missing prerequisite. |

## What a fix CAN do at the compute-runtime layer

Given that the kernel-side bind is unfixable from userspace, compute-runtime has two realistic options:

### Option A — skip eager makeResident for peer-imported allocs

The minimal source change. In `Context::makeMemoryResident`, when `getPeerAllocation` returns a peer-imported `GraphicsAllocation`, return `ZE_RESULT_SUCCESS` without calling `memoryOperationsIface->makeResident`. The DMA-buf import has already mapped the BO into the peer device's address space at the source VA, which is what residency means at the user level. Lazy bind happens later when a command list actually submits work that needs the BO resident.

**Validated on the rig (build #N+1, with this patch only, no others):**
- 2-device `sycl::context()` → **OK**
- 4-device `sycl::context()` → **OK**
- 2-device + 4-device `sycl::context()` are reproducible PASS

**Does NOT fix:**
- Cross-device `q1.memcpy(b_on_dev1, a_on_dev0)` — the BCS submission path also calls `makeResident` for the peer allocation and that also hits the same xe EINVAL. So actual cross-device kernel workloads still fail.

This is still a worthwhile PR because:
- It fixes the `UR_RESULT_ERROR_UNKNOWN` thrown from `sycl::context()` itself, which is what breaks `sycl-ls`, `llama-cli --list-devices`, vLLM device discovery, and any other tool that tries to enumerate multiple BMG cards. These tools don't actually use cross-device memory — they just need the context to construct.
- It makes V2-adapter behavior match V1-adapter behavior at this exact decision point: V1 also ignores the failure here.
- It's the smallest possible change, easy to review and revert.

The diff:

```diff
diff --git a/level_zero/core/source/context/context.cpp b/level_zero/core/source/context/context.cpp
@@ -686,12 +686,21 @@ ze_result_t Context::makeMemoryResident(ze_device_handle_t hDevice, void *ptr, s
     auto allocation = device->getDriverHandle()->getDriverSystemMemoryAllocation(
         ptr,
         size,
         neoDevice->getRootDeviceIndex(),
         nullptr);
+    bool isPeerImportedAllocation = false;
     if (allocation == nullptr) {
         NEO::SvmAllocationData *allocData = nullptr;
         bool foundBuffer = this->driverHandle->findAllocationDataForRange(ptr, size, allocData);
         if (foundBuffer) {
             uintptr_t alignedPtr = reinterpret_cast<uintptr_t>(ptr);
             allocation = this->driverHandle->getPeerAllocation(device, allocData, ptr, &alignedPtr, nullptr, false);
+            isPeerImportedAllocation = (allocation != nullptr);
         }
         if (allocation == nullptr) {
             return ZE_RESULT_ERROR_INVALID_ARGUMENT;
         }
     }
+    // Peer-imported allocations have their address-space mapping established by
+    // getPeerAllocation's DMA-buf import. An additional eager per-engine bind via
+    // memoryOperationsIface->makeResident can be rejected by some kernel drivers
+    // (xe / BMG: EINVAL on vmBind of peer-imported BOs) and breaks UR V2 adapter's
+    // multi-device context construction handshake. The actual residency is
+    // established lazily when the peer alloc is used in a command-list submission.
+    if (isPeerImportedAllocation) {
+        return ZE_RESULT_SUCCESS;
+    }
     if (allocation->isLockedMemory()) {
         return ZE_RESULT_ERROR_INVALID_ARGUMENT;
     }
```

The patch in master applies the same way; line numbers shift slightly but the surrounding code is identical.

### Option B — fix the V2 UR adapter to not call `zeContextMakeMemoryResident` on peer devices during multi-device context construction

This is the right architectural fix but lives in `oneapi-src/unified-runtime`, not compute-runtime. A PR there could detect that the destination device is a non-source device in the context and skip the residency mirror. compute-runtime can't influence this from its side.

## Recommendation

Submit Option A upstream as **`fix: skip eager peer-import makeResident in Context::makeMemoryResident`** with the body above. Cite #921, #916, ggml-org/llama.cpp#21747, and note that this fixes the multi-device-enumeration failure for any BMG-using tool. Real cross-device workloads still need either kernel-side xe driver progress on peer-imported BO bind, or for end users to fall back to OpenCL (`ONEAPI_DEVICE_SELECTOR='opencl:gpu'`) which doesn't go through this code path.

For the local rig: drop the `020-revert-dc85f33e49-usm-compression-peer-access.patch` from `~/build/compute-runtime-pkg/PKGBUILD` (it's net-harmful) and add Option A's patch instead. Keep the BMG one-liner (`initializeInternalEngineImmediately()=true`) — it's still required to make single-device init reliable.

## Open questions

1. Is the xe `vmBind EINVAL` on peer-imported BO a known kernel limitation tracked anywhere? — worth posting on intel-xe@lists.freedesktop.org with the trace.
2. Does upstream xe-next have the fix? — worth checking `git log --oneline` in `drivers/gpu/drm/xe/` for "p2p" / "external" / "dma-buf" since 6.18 baseline.
3. Does ARC A770 (also affected per #916) show the same exact failure mode? It's i915 driver, not xe — likely a different root cause, even if the user-visible symptom looks the same.

  
</details>

**Comment by F3zz1k** [comment]
Reported upstream to kernel driver: https://gitlab.freedesktop.org/drm/xe/kernel/-/work_items/8022
A quick search shows some rework on the relevant parts of the code so there may already be a fix incoming, let's see what they say over there.

**Comment by Stoney49th** [comment]
@F3zz1k  Thank you for the effort! Are you in a VM with your 4 cards, or is this bare metal manjaro? I also run manjaro 7.0.3, but in a VM with the GPUs (and an additonal AMD one...) passed through fully, without mounting them on the host via SRIOV VFDevs. Not sure if this is related, but maybe thats part of the problem causing a different kernel dma buffer handling?

**Comment by F3zz1k** [comment]
@Stoney49th Bare metal. I used the intel docker initially but recompiling things natively can recreate the problem.

**Comment by ClancyBuf** [comment]
Arc Pro B60 x2: zeDeviceCanAccessPeer returns YES but peer zeCommandListAppendMemoryCopy fails with ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY

Hardware:
- 2x Intel Arc Pro B60, device ID 8086:e211
- AMD AM5 / PCIe 5.0 motherboard
- Both GPUs linked at PCIe 5.0 x8

OS / stack:
- Fedora 44
- Kernel: 7.0.8-200.fc44.x86_64
- Driver: xe
- intel-compute-runtime-26.09.37435.12-1.fc44.x86_64
- intel-level-zero-26.09.37435.12-1.fc44.x86_64
- oneapi-level-zero-1.28.2-2.fc44.x86_64

Platform config:
- ACS disabled on relevant PCIe ports:
  - 00:01.1 = 0000
  - 02:01.0 = 0000
  - 00:01.3 = 0000
  - 07:01.0 = 0000
- IOMMU passthrough enabled:
  - iommu: Default domain type: Passthrough
- Level Zero sees both B60s under one driver.

Observed:
- zeDeviceCanAccessPeer(dev0, dev1) returns YES
- zeDeviceCanAccessPeer(dev1, dev0) returns YES
- Host -> GPU0 memory copy succeeds
- GPU0 -> GPU1 zeCommandListAppendMemoryCopy fails with:
  ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY / 0x70000003
- zeContextMakeMemoryResident(ctx, devs[0], d1, bytes) also fails with:
  ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY / 0x70000003
- Failure occurs with a 4 MiB allocation, so this does not appear to be actual VRAM exhaustion.
- Failure occurs on both compute queue and copy queue.

Expected:
- If zeDeviceCanAccessPeer reports YES, a basic peer device-memory copy should succeed, or the peer capability query should report NO.

Actual:
- Peer capability is reported as YES, but actual peer memory mapping/copy fails.

**Comment by ClancyBuf** [comment]
https://gitlab.freedesktop.org/drm/xe/kernel/-/work_items/8039

**Comment by F3zz1k** [comment]
Just updating: Latest updates do not resolve this issue.  No fixes in as of kernel 7.1-rc4.  Compiling latest llama.cpp improved my per-card performance significantly but multi-gpu is still essentially broken (except using vulkan backend which has atrocious, even negative performance gains per added gpu).

**Comment by F3zz1k** [comment]
Small update, the latest kernel rc does fix the main blocker I was hitting above but p2p reads are all messed up due to compression.  Testing some changes to compute-runtime which may, in combination with rc kernel, get things somewhat working:
```
  +    const bool multiDeviceContext = (memoryProperties.rootDeviceIndices.size() > 1);
       if (compressionEnabled && memoryProperties.device) {
           auto *releaseHelper = memoryProperties.device->getReleaseHelper();
           if (releaseHelper && !releaseHelper->isUsmCompressionSupportedOnPeerAccess() &&
  -            memoryProperties.device->hasAnyPeerAccess().value_or(false)) {
  +            (memoryProperties.device->hasAnyPeerAccess().value_or(false) || multiDeviceContext)) {
               compressionEnabled = false;
           }
       }  
```

**Comment by F3zz1k** [comment]
## Multi-device USM device alloc on BMG: peer-read returns garbage from compression-on-peer race

`SVMAllocsManager::createUnifiedMemoryAllocation` disables compression for peer-imported USM allocations via a guard introduced in dc85f33e49 and refactored in 26.18. The guard tests `device->hasAnyPeerAccess().value_or(false)`.

That `std::optional<bool>` is populated lazily by `initializePeerAccessForDevices` at driver init. For the **first** USM device allocation in a multi-device L0 context the value is observed as `Some(false)` — the disable arm is skipped, the BO is allocated compressed, and any later peer-import returns the compressed bytes through dma-buf without surface metadata.

### Repro (BMG, 2× Arc Pro B70, Linux 7.1-rc4 + xe, intel-compute-runtime 26.18.38308.1)

`multi_kernel_test.cpp` (single sycl::malloc_device on dev0 + q_dev1.memcpy):

```
$ ZE_AFFINITY_MASK=0,1 ./multi_kernel_test
[A] single-device           PASS
[B] multi-dev ctx, same dev PASS
[C] dev0 writer / dev1 read FAIL — host[0..3] = 0,0,0,0

$ NEOReadDebugKeys=1 RenderCompressedBuffersEnabled=0 ZE_AFFINITY_MASK=0,1 ./multi_kernel_test
[C] dev0 writer / dev1 read PASS — host[0..3] = 100,101,102,103
```

OpenCL backend aborts at `enqueue_svm.h:308` `UNRECOVERABLE_IF(!allocation)` for the same case.

### Evidence

`fprintf` at the top of `createUnifiedMemoryAllocation` (added for diagnosis):

```
[USM-DBG] createUnif rdi=0 comp_pre=1 nRDIs=2 peerHas=1 peer=0  <-- first alloc: Some(false)
[USM-DBG] createUnif rdi=0 comp_pre=1 nRDIs=2 peerHas=1 peer=1  <-- subsequent allocs
```

Kernel side is correct — bpftrace confirms `xe_dma_buf_map` returns sg_tables with peer-BAR addresses and `xe_pt_insert_entry` commits PTEs at those addresses. The peer reads the *right physical location*; the bytes there are compressed.

### Patch

Single-line conditional addition. Gate also on `memoryProperties.rootDeviceIndices.size() > 1` — that's known synchronously at allocation time and conservatively disables compression for any multi-device context BO (which can become peer-imported later regardless of the current cache state).

```diff
+    const bool multiDeviceContext = (memoryProperties.rootDeviceIndices.size() > 1);
     if (compressionEnabled && memoryProperties.device) {
         auto *releaseHelper = memoryProperties.device->getReleaseHelper();
         if (releaseHelper && !releaseHelper->isUsmCompressionSupportedOnPeerAccess() &&
-            memoryProperties.device->hasAnyPeerAccess().value_or(false)) {
+            (memoryProperties.device->hasAnyPeerAccess().value_or(false) || multiDeviceContext)) {
             compressionEnabled = false;
         }
     }
```

(For 26.18: same `|| multiDeviceContext` addition to the `preferCompressed = false` gate at `unified_memory_manager.cpp:521-525`.)

Verified by rebuilding 26.05 with the patch, loading via `LD_LIBRARY_PATH`: repro case C passes 5/5 runs. Reverting the patch on the same build: returns to FAIL.

### Related

- vllm-project/vllm#41663 (same hardware, downstream symptom on TP=2)
- #916, #922 — adjacent multi-device BMG/A770 issues
- Kernel-side prerequisite (xe_dma_buf_pin -EINVAL) fixed by Leon Romanovsky's "dma-buf: Always build with DMABUF_MOVE_NOTIFY" — in mainline 7.1

**Comment by F3zz1k** [comment]
TLDR until patch is merged:
```
1. kernel ≥ Linux 7.1 (Manjaro linux71 — Leon's MOVE_NOTIFY merged in mainline 7.1)
2. intel-compute-runtime ≥ 26.18 (from extra repo, with pin removed)
3. oneAPI 2026.0+, rebuild your SYCL apps against the new libsycl.so.9 if needed
4. disable VRAM compression for multi-device SYCL workloads:
NEOReadDebugKeys=1 RenderCompressedBuffersEnabled=0
```

**Comment by arthw** [comment]
@jchodor 
Since this issue impacts all multiple GPUs user cases and we have narrowed down the regression version.
Is it possible to assign to developer to check it?

Thank you!

**Comment by jwarchul** [comment]
Hi @F3zz1k, @ClancyBuf, @Stoney49th, @arthw, 

Thank you all for reporting this.

There are two distinct issues described here.

1. UR_RESULT_ERROR_UNKNOWN - This is the same issue as in #916. It is already fixed in kernel 7.1+, and for pre-7.1 kernels it is addressed in e91243a9d03de849f45d8b862a62afd4424cff8b.

2. Compression-related issue (the one that the `RenderCompressedBuffersEnabled=0` flag helps with) - This is a regression introduced in e4e871c1af3fb125424f0b067488d238e0f599fd. It should be resolved by 258518f8039afba59c46d98bb7f6f068d12f026d. It also requires kernel 7.1+.

Please let us know whether these updates resolve all of your problems, or if anything still remains.

Thanks again for the report and the great collaboration!

**Comment by F3zz1k** [comment]
Tested https://github.com/intel/compute-runtime/commit/258518f8039afba59c46d98bb7f6f068d12f026d on 7.1 rc and can confirm the issue is resolved.  Sections that are accessed P2P are now left decompressed while the rest stays compressed.  Thanks for the fix, @jwarchul .

If anyone else hits this issue before the next release, update to 7.1(latest rc is fine) kernel and use env variables `NEOReadDebugKeys=1 RenderCompressedBuffersEnabled=0`.

**Comment by mjsabby** [comment]
@F3zz1k does this mean Intel B70's can actually do P2P DMA if the kernel allow lists the chipset? Also maybe question for @arthw and @jwarchul

**Comment by F3zz1k** [comment]
> [@F3zz1k](https://github.com/F3zz1k) does this mean Intel B70's can actually do P2P DMA if the kernel allow lists the chipset? Also maybe question for [@arthw](https://github.com/arthw) and [@jwarchul](https://github.com/jwarchul)

Yes, though make sure you have the latest 7.1 kernel as I did have some issues with compression when just using the patch to have them listed. Temporary workaround for me was to turn off compression though there's since been some work on only decompressing the parts that are used p2p.

**Comment by mjsabby** [comment]
Verified P2P works on AM5 host with 7.1.2 kernel, Intel Compute 26.22.38646.4
